version: "3.7"
services: 
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD='admin'
    networks:
      - network_aplication

  api:
    build: "./cadastro-transacao-service"
    container_name: api-container
    restart: always
    ports: 
      - "9091:8080"
    networks: 
     - network_aplication
    environment: 
      - SPRING_PROFILES_ACTIVE=prod
      - DATASOURCE_URL=jdbc:mysql://db:3306/sys?useTimezone=true&serverTimezone=UTC
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=admin

  web:
    build: "./pages"
    container_name: pages-container
    restart: always
    ports:
      - "9090:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks: 
    - network_aplication

networks: 
  network_aplication:
   driver: bridge




